-- NarrativeContent.lua
-- MASSIVE BitLife-style text content library
-- Contains 1500+ narrative variations for rich storytelling
-- NO LOGIC - PURE CONTENT ONLY

local NarrativeContent = {}

----------------------------------------------------------------------
-- STAT NARRATIVE VARIATIONS (40+ per bucket = 640+ total stat lines)
----------------------------------------------------------------------

NarrativeContent.StatNarrative = {
	Happiness = {
		up = {
			small = {
				"Your happiness ticked up a bit (+%d%%, now %d%%).",
				"You're feeling a little more cheerful (+%d%%, now %d%%).",
				"A small smile crept across your face (+%d%%, now %d%%).",
				"Things are looking slightly brighter (+%d%%, now %d%%).",
				"Your mood improved just a touch (+%d%%, now %d%%).",
				"You feel marginally happier about life (+%d%%, now %d%%).",
				"A tiny weight lifted from your shoulders (+%d%%, now %d%%).",
				"Your spirits rose ever so slightly (+%d%%, now %d%%).",
				"Life doesn't seem quite so bad (+%d%%, now %d%%).",
				"You caught yourself humming a tune (+%d%%, now %d%%).",
				"A flicker of joy passed through you (+%d%%, now %d%%).",
				"Your outlook improved a tad (+%d%%, now %d%%).",
				"You feel a bit more optimistic (+%d%%, now %d%%).",
				"A gentle warmth filled your chest (+%d%%, now %d%%).",
				"You're slightly more content with life (+%d%%, now %d%%).",
				"Things could be worse, you thought with a smile (+%d%%, now %d%%).",
				"A small victory for your mental health (+%d%%, now %d%%).",
				"You found a reason to smile today (+%d%%, now %d%%).",
				"Your worries faded just a little (+%d%%, now %d%%).",
				"You're feeling marginally better about everything (+%d%%, now %d%%).",
			},
			medium = {
				"Your happiness noticeably improved (+%d%%, now %d%%).",
				"Life feels brighter than before (+%d%%, now %d%%).",
				"You're definitely feeling better (+%d%%, now %d%%).",
				"A genuine smile appeared on your face (+%d%%, now %d%%).",
				"Your mood took a noticeable turn for the better (+%d%%, now %d%%).",
				"You feel genuinely happier now (+%d%%, now %d%%).",
				"Things are looking up considerably (+%d%%, now %d%%).",
				"You caught yourself actually enjoying life (+%d%%, now %d%%).",
				"A wave of contentment washed over you (+%d%%, now %d%%).",
				"Your spirits are noticeably higher (+%d%%, now %d%%).",
				"You're walking with a spring in your step (+%d%%, now %d%%).",
				"Life doesn't seem so overwhelming anymore (+%d%%, now %d%%).",
				"You feel like things might actually work out (+%d%%, now %d%%).",
				"A solid boost to your overall happiness (+%d%%, now %d%%).",
				"You're feeling pretty good about things (+%d%%, now %d%%).",
				"Your outlook on life improved significantly (+%d%%, now %d%%).",
				"You found yourself laughing more easily (+%d%%, now %d%%).",
				"The weight on your chest got noticeably lighter (+%d%%, now %d%%).",
				"You're starting to enjoy the little things again (+%d%%, now %d%%).",
				"A meaningful improvement to your wellbeing (+%d%%, now %d%%).",
			},
			big = {
				"You felt a huge boost of joy (+%d%%, now %d%%).",
				"This really lifted your spirits (+%d%%, now %d%%).",
				"You're beaming with happiness (+%d%%, now %d%%).",
				"Life suddenly feels wonderful (+%d%%, now %d%%).",
				"You're practically glowing with joy (+%d%%, now %d%%).",
				"Everything feels right in the world (+%d%%, now %d%%).",
				"You can't stop smiling (+%d%%, now %d%%).",
				"Pure happiness flooded through you (+%d%%, now %d%%).",
				"You feel like you could take on the world (+%d%%, now %d%%).",
				"Your heart is soaring (+%d%%, now %d%%).",
				"You've never felt this good in a while (+%d%%, now %d%%).",
				"Joy is radiating from every pore (+%d%%, now %d%%).",
				"This was exactly what you needed (+%d%%, now %d%%).",
				"You're on cloud nine (+%d%%, now %d%%).",
				"Happiness hit you like a wave (+%d%%, now %d%%).",
				"You feel genuinely alive and happy (+%d%%, now %d%%).",
				"Everything seems possible now (+%d%%, now %d%%).",
				"You're dancing on the inside (+%d%%, now %d%%).",
				"Life is beautiful and you finally see it (+%d%%, now %d%%).",
				"You want to share this feeling with everyone (+%d%%, now %d%%).",
			},
			huge = {
				"This was a life-changing moment of happiness (+%d%%, now %d%%).",
				"You've rarely felt this good (+%d%%, now %d%%).",
				"Absolute euphoria washed over you (+%d%%, now %d%%).",
				"You'll remember this feeling forever (+%d%%, now %d%%).",
				"This is what living feels like (+%d%%, now %d%%).",
				"Pure, unfiltered joy consumed you (+%d%%, now %d%%).",
				"You've reached peak happiness (+%d%%, now %d%%).",
				"Nothing could bring you down right now (+%d%%, now %d%%).",
				"This is the happiest you've ever been (+%d%%, now %d%%).",
				"Your soul is singing with joy (+%d%%, now %d%%).",
				"Everything in life led to this perfect moment (+%d%%, now %d%%).",
				"You want to freeze this feeling forever (+%d%%, now %d%%).",
				"Tears of pure happiness ran down your face (+%d%%, now %d%%).",
				"You feel blessed beyond measure (+%d%%, now %d%%).",
				"Life will never be the same after this (+%d%%, now %d%%).",
				"You're floating on pure bliss (+%d%%, now %d%%).",
				"Every cell in your body is celebrating (+%d%%, now %d%%).",
				"This is what true happiness feels like (+%d%%, now %d%%).",
				"You've unlocked a new level of joy (+%d%%, now %d%%).",
				"The universe finally smiled upon you (+%d%%, now %d%%).",
			},
		},
		down = {
			small = {
				"Your happiness dipped a little (-%d%%, now %d%%).",
				"You're slightly less happy than before (-%d%%, now %d%%).",
				"A small frown replaced your smile (-%d%%, now %d%%).",
				"Your mood soured just a bit (-%d%%, now %d%%).",
				"Things feel marginally worse (-%d%%, now %d%%).",
				"A tiny cloud appeared over your day (-%d%%, now %d%%).",
				"You're not quite as cheerful (-%d%%, now %d%%).",
				"Your spirits dropped slightly (-%d%%, now %d%%).",
				"The day got a little grayer (-%d%%, now %d%%).",
				"You let out a small sigh (-%d%%, now %d%%).",
				"A minor setback for your mood (-%d%%, now %d%%).",
				"You feel slightly deflated (-%d%%, now %d%%).",
				"Your smile faded a bit (-%d%%, now %d%%).",
				"Life feels marginally heavier (-%d%%, now %d%%).",
				"A twinge of sadness crept in (-%d%%, now %d%%).",
				"You're not as upbeat as before (-%d%%, now %d%%).",
				"Your optimism dimmed slightly (-%d%%, now %d%%).",
				"A small weight settled on your shoulders (-%d%%, now %d%%).",
				"Things aren't quite as bright (-%d%%, now %d%%).",
				"Your joy flickered momentarily (-%d%%, now %d%%).",
			},
			medium = {
				"This took a toll on your happiness (-%d%%, now %d%%).",
				"You feel noticeably less happy (-%d%%, now %d%%).",
				"Your mood dropped considerably (-%d%%, now %d%%).",
				"A wave of sadness hit you (-%d%%, now %d%%).",
				"Things feel genuinely worse now (-%d%%, now %d%%).",
				"Your spirits sank noticeably (-%d%%, now %d%%).",
				"You're struggling to stay positive (-%d%%, now %d%%).",
				"The joy drained from your face (-%d%%, now %d%%).",
				"Life feels heavier than before (-%d%%, now %d%%).",
				"You can't shake this down feeling (-%d%%, now %d%%).",
				"Your heart feels notably heavier (-%d%%, now %d%%).",
				"Sadness settled in for a while (-%d%%, now %d%%).",
				"You're finding it hard to smile (-%d%%, now %d%%).",
				"This really dampened your spirits (-%d%%, now %d%%).",
				"Your outlook darkened significantly (-%d%%, now %d%%).",
				"You feel genuinely unhappy (-%d%%, now %d%%).",
				"The world seems grayer now (-%d%%, now %d%%).",
				"You're carrying this weight with you (-%d%%, now %d%%).",
				"Your usual cheerfulness is gone (-%d%%, now %d%%).",
				"This was a real blow to your mood (-%d%%, now %d%%).",
			},
			big = {
				"Your happiness plummeted (-%d%%, now %d%%).",
				"This really dragged your mood down (-%d%%, now %d%%).",
				"You feel genuinely miserable (-%d%%, now %d%%).",
				"A dark cloud settled over you (-%d%%, now %d%%).",
				"Your spirits crashed hard (-%d%%, now %d%%).",
				"You can barely find the will to smile (-%d%%, now %d%%).",
				"Life feels overwhelmingly sad (-%d%%, now %d%%).",
				"This hit you harder than expected (-%d%%, now %d%%).",
				"You're struggling to see the bright side (-%d%%, now %d%%).",
				"Your heart feels incredibly heavy (-%d%%, now %d%%).",
				"Joy seems like a distant memory (-%d%%, now %d%%).",
				"You feel utterly deflated (-%d%%, now %d%%).",
				"This knocked the wind out of you (-%d%%, now %d%%).",
				"Your world got significantly darker (-%d%%, now %d%%).",
				"You're fighting back tears (-%d%%, now %d%%).",
				"Happiness feels impossible right now (-%d%%, now %d%%).",
				"This really broke something inside (-%d%%, now %d%%).",
				"You feel hollowed out (-%d%%, now %d%%).",
				"Your usual resilience crumbled (-%d%%, now %d%%).",
				"Getting through the day feels impossible (-%d%%, now %d%%).",
			},
			huge = {
				"You were devastated by this (-%d%%, now %d%%).",
				"This crushed your happiness (-%d%%, now %d%%).",
				"You've hit rock bottom emotionally (-%d%%, now %d%%).",
				"Complete despair washed over you (-%d%%, now %d%%).",
				"You don't know how to go on (-%d%%, now %d%%).",
				"This destroyed any joy you had left (-%d%%, now %d%%).",
				"You feel utterly broken inside (-%d%%, now %d%%).",
				"The world lost all its color (-%d%%, now %d%%).",
				"You can't stop the tears (-%d%%, now %d%%).",
				"Everything feels hopeless (-%d%%, now %d%%).",
				"Your heart shattered into pieces (-%d%%, now %d%%).",
				"You've never felt this low (-%d%%, now %d%%).",
				"Happiness seems like a cruel joke (-%d%%, now %d%%).",
				"You're questioning everything (-%d%%, now %d%%).",
				"This wound will take time to heal (-%d%%, now %d%%).",
				"Your soul feels crushed (-%d%%, now %d%%).",
				"Getting out of bed seems impossible (-%d%%, now %d%%).",
				"You feel completely empty inside (-%d%%, now %d%%).",
				"The light went out of your eyes (-%d%%, now %d%%).",
				"You've lost the will to smile (-%d%%, now %d%%).",
			},
		},
	},

	Health = {
		up = {
			small = {
				"You feel a bit healthier (+%d%%, now %d%%).",
				"Your health ticked up slightly (+%d%%, now %d%%).",
				"You're feeling marginally better physically (+%d%%, now %d%%).",
				"Your body thanks you (+%d%%, now %d%%).",
				"A small health boost came your way (+%d%%, now %d%%).",
				"You're slightly more energetic (+%d%%, now %d%%).",
				"Your immune system perked up (+%d%%, now %d%%).",
				"You feel a touch more vital (+%d%%, now %d%%).",
				"Your stamina improved a bit (+%d%%, now %d%%).",
				"You're breathing a little easier (+%d%%, now %d%%).",
				"A minor health improvement (+%d%%, now %d%%).",
				"You feel slightly less tired (+%d%%, now %d%%).",
				"Your body's recovering nicely (+%d%%, now %d%%).",
				"You notice you're feeling better (+%d%%, now %d%%).",
				"Small steps toward better health (+%d%%, now %d%%).",
				"Your vitality is slowly returning (+%d%%, now %d%%).",
				"You're on the mend (+%d%%, now %d%%).",
				"Your wellness improved marginally (+%d%%, now %d%%).",
				"You feel a tad more alive (+%d%%, now %d%%).",
				"Your energy levels rose slightly (+%d%%, now %d%%).",
			},
			medium = {
				"Your health noticeably improved (+%d%%, now %d%%).",
				"You feel stronger and healthier (+%d%%, now %d%%).",
				"Your body is responding well (+%d%%, now %d%%).",
				"You're definitely feeling more vital (+%d%%, now %d%%).",
				"A solid boost to your physical health (+%d%%, now %d%%).",
				"Your energy levels are up (+%d%%, now %d%%).",
				"You feel genuinely healthier (+%d%%, now %d%%).",
				"Your body is healing nicely (+%d%%, now %d%%).",
				"You're noticeably more energetic (+%d%%, now %d%%).",
				"Your vitality has clearly improved (+%d%%, now %d%%).",
				"You're feeling strong and capable (+%d%%, now %d%%).",
				"Your physical condition is improving (+%d%%, now %d%%).",
				"You're bouncing back well (+%d%%, now %d%%).",
				"Your body's thanking you for this (+%d%%, now %d%%).",
				"You feel more robust than before (+%d%%, now %d%%).",
				"Health gains are visible (+%d%%, now %d%%).",
				"You're feeling fit and healthy (+%d%%, now %d%%).",
				"Your stamina has notably increased (+%d%%, now %d%%).",
				"You're regaining your strength (+%d%%, now %d%%).",
				"Your wellness is clearly on the rise (+%d%%, now %d%%).",
			},
			big = {
				"Your health made a big recovery (+%d%%, now %d%%).",
				"You feel renewed physically (+%d%%, now %d%%).",
				"Your body is thriving (+%d%%, now %d%%).",
				"You're in excellent physical shape (+%d%%, now %d%%).",
				"A major health breakthrough (+%d%%, now %d%%).",
				"You feel like a new person (+%d%%, now %d%%).",
				"Your vitality is soaring (+%d%%, now %d%%).",
				"You're bursting with energy (+%d%%, now %d%%).",
				"Your health has transformed (+%d%%, now %d%%).",
				"You feel incredibly strong (+%d%%, now %d%%).",
				"Your body is performing at its best (+%d%%, now %d%%).",
				"You've never felt this healthy (+%d%%, now %d%%).",
				"A remarkable recovery occurred (+%d%%, now %d%%).",
				"Your physical wellness is exceptional (+%d%%, now %d%%).",
				"You're radiating good health (+%d%%, now %d%%).",
				"Your immune system is unstoppable (+%d%%, now %d%%).",
				"You feel like you could run a marathon (+%d%%, now %d%%).",
				"Your energy is through the roof (+%d%%, now %d%%).",
				"You're in peak physical condition (+%d%%, now %d%%).",
				"Your health bounce-back was impressive (+%d%%, now %d%%).",
			},
			huge = {
				"This turned your health around (+%d%%, now %d%%).",
				"You bounced back in a major way (+%d%%, now %d%%).",
				"A miraculous health transformation (+%d%%, now %d%%).",
				"You feel reborn physically (+%d%%, now %d%%).",
				"Your body has fully healed (+%d%%, now %d%%).",
				"You're in the best shape of your life (+%d%%, now %d%%).",
				"This saved your health (+%d%%, now %d%%).",
				"You feel invincible physically (+%d%%, now %d%%).",
				"Your vitality hit maximum levels (+%d%%, now %d%%).",
				"A complete health renaissance (+%d%%, now %d%%).",
				"You've unlocked superhuman energy (+%d%%, now %d%%).",
				"Your body is a temple again (+%d%%, now %d%%).",
				"You feel decades younger (+%d%%, now %d%%).",
				"Health has never felt this good (+%d%%, now %d%%).",
				"You're operating at 110%% (+%d%%, now %d%%).",
				"Your wellness is off the charts (+%d%%, now %d%%).",
				"This was a life-saving health boost (+%d%%, now %d%%).",
				"You feel like you've been given new life (+%d%%, now %d%%).",
				"Your physical recovery is nothing short of miraculous (+%d%%, now %d%%).",
				"You're the healthiest you've ever been (+%d%%, now %d%%).",
			},
		},
		down = {
			small = {
				"Your health slipped a bit (-%d%%, now %d%%).",
				"You aren't feeling quite as healthy (-%d%%, now %d%%).",
				"A minor health setback (-%d%%, now %d%%).",
				"You feel slightly under the weather (-%d%%, now %d%%).",
				"Your body isn't thanking you for that (-%d%%, now %d%%).",
				"Your energy dipped a little (-%d%%, now %d%%).",
				"You're feeling marginally worse (-%d%%, now %d%%).",
				"A small toll on your health (-%d%%, now %d%%).",
				"Your stamina dropped slightly (-%d%%, now %d%%).",
				"You feel a bit more tired (-%d%%, now %d%%).",
				"Your wellness declined a touch (-%d%%, now %d%%).",
				"You're not at 100%% today (-%d%%, now %d%%).",
				"A minor ding to your health (-%d%%, now %d%%).",
				"Your body's feeling it (-%d%%, now %d%%).",
				"You feel slightly drained (-%d%%, now %d%%).",
				"Your vitality took a small hit (-%d%%, now %d%%).",
				"You're running a bit low on energy (-%d%%, now %d%%).",
				"Your immune system hiccupped (-%d%%, now %d%%).",
				"You're feeling a tad fragile (-%d%%, now %d%%).",
				"Not the best day for your health (-%d%%, now %d%%).",
			},
			medium = {
				"This hurt your health (-%d%%, now %d%%).",
				"You feel noticeably worse physically (-%d%%, now %d%%).",
				"Your health took a hit (-%d%%, now %d%%).",
				"You're definitely not feeling well (-%d%%, now %d%%).",
				"Your body is struggling (-%d%%, now %d%%).",
				"This set back your health (-%d%%, now %d%%).",
				"You feel genuinely unwell (-%d%%, now %d%%).",
				"Your energy is notably low (-%d%%, now %d%%).",
				"Your vitality dropped significantly (-%d%%, now %d%%).",
				"You're paying for this physically (-%d%%, now %d%%).",
				"Your health declined noticeably (-%d%%, now %d%%).",
				"You feel weakened by this (-%d%%, now %d%%).",
				"Your body's sending warning signals (-%d%%, now %d%%).",
				"You're not bouncing back as quickly (-%d%%, now %d%%).",
				"This was hard on your system (-%d%%, now %d%%).",
				"Your physical condition worsened (-%d%%, now %d%%).",
				"You feel drained and tired (-%d%%, now %d%%).",
				"Your wellness took a real hit (-%d%%, now %d%%).",
				"You're struggling to keep up (-%d%%, now %d%%).",
				"Your health is clearly suffering (-%d%%, now %d%%).",
			},
			big = {
				"Your health took a serious hit (-%d%%, now %d%%).",
				"This really damaged your health (-%d%%, now %d%%).",
				"You feel genuinely ill (-%d%%, now %d%%).",
				"Your body is in rough shape (-%d%%, now %d%%).",
				"This was devastating to your health (-%d%%, now %d%%).",
				"You can barely function physically (-%d%%, now %d%%).",
				"Your vitality crashed hard (-%d%%, now %d%%).",
				"You feel terrible physically (-%d%%, now %d%%).",
				"Your health is in serious decline (-%d%%, now %d%%).",
				"You're struggling to stay upright (-%d%%, now %d%%).",
				"This really wore you down (-%d%%, now %d%%).",
				"Your body is screaming for rest (-%d%%, now %d%%).",
				"You feel broken physically (-%d%%, now %d%%).",
				"Your energy completely tanked (-%d%%, now %d%%).",
				"Recovery will take time (-%d%%, now %d%%).",
				"You're in bad shape (-%d%%, now %d%%).",
				"Your immune system is shot (-%d%%, now %d%%).",
				"You feel like you've been hit by a truck (-%d%%, now %d%%).",
				"Your health is hanging by a thread (-%d%%, now %d%%).",
				"This did serious damage (-%d%%, now %d%%).",
			},
			huge = {
				"Your health collapsed after this (-%d%%, now %d%%).",
				"This was a critical blow to your health (-%d%%, now %d%%).",
				"You're fighting for your health (-%d%%, now %d%%).",
				"Your body is failing you (-%d%%, now %d%%).",
				"This nearly destroyed your health (-%d%%, now %d%%).",
				"You're in critical condition (-%d%%, now %d%%).",
				"Your vitality flatlined (-%d%%, now %d%%).",
				"You've never felt this sick (-%d%%, now %d%%).",
				"This was life-threateningly serious (-%d%%, now %d%%).",
				"Your health hit rock bottom (-%d%%, now %d%%).",
				"You're barely holding on physically (-%d%%, now %d%%).",
				"Your body gave out (-%d%%, now %d%%).",
				"This pushed you to the brink (-%d%%, now %d%%).",
				"You need serious medical attention (-%d%%, now %d%%).",
				"Your health may never fully recover (-%d%%, now %d%%).",
				"This was catastrophic for your body (-%d%%, now %d%%).",
				"You feel like you're dying (-%d%%, now %d%%).",
				"Your physical state is dire (-%d%%, now %d%%).",
				"Every breath is a struggle (-%d%%, now %d%%).",
				"You've reached a health crisis (-%d%%, now %d%%).",
			},
		},
	},

	Smarts = {
		up = {
			small = {
				"You feel a little sharper (+%d%%, now %d%%).",
				"You picked up a bit of knowledge (+%d%%, now %d%%).",
				"Your mind expanded slightly (+%d%%, now %d%%).",
				"You learned something new (+%d%%, now %d%%).",
				"A small boost to your intellect (+%d%%, now %d%%).",
				"Your thinking got clearer (+%d%%, now %d%%).",
				"You feel marginally smarter (+%d%%, now %d%%).",
				"Your brain appreciated that (+%d%%, now %d%%).",
				"A minor mental upgrade (+%d%%, now %d%%).",
				"Your knowledge base grew a bit (+%d%%, now %d%%).",
				"You're thinking a touch more clearly (+%d%%, now %d%%).",
				"Your intelligence ticked upward (+%d%%, now %d%%).",
				"You absorbed some useful info (+%d%%, now %d%%).",
				"Your cognitive abilities improved slightly (+%d%%, now %d%%).",
				"A small win for your brain (+%d%%, now %d%%).",
				"You're slightly more informed (+%d%%, now %d%%).",
				"Your mental acuity sharpened a bit (+%d%%, now %d%%).",
				"Knowledge gained, even if just a little (+%d%%, now %d%%).",
				"Your neurons fired up a touch (+%d%%, now %d%%).",
				"You feel a tad wiser (+%d%%, now %d%%).",
			},
			medium = {
				"Your smarts improved noticeably (+%d%%, now %d%%).",
				"You learned a lot from this (+%d%%, now %d%%).",
				"Your mind is sharper than before (+%d%%, now %d%%).",
				"A solid boost to your intelligence (+%d%%, now %d%%).",
				"Your knowledge expanded significantly (+%d%%, now %d%%).",
				"You feel genuinely smarter (+%d%%, now %d%%).",
				"Your brain is working better (+%d%%, now %d%%).",
				"Your thinking has leveled up (+%d%%, now %d%%).",
				"You're noticeably more knowledgeable (+%d%%, now %d%%).",
				"Your cognitive growth is evident (+%d%%, now %d%%).",
				"You absorbed that knowledge well (+%d%%, now %d%%).",
				"Your mental capacity increased (+%d%%, now %d%%).",
				"You're connecting dots more easily (+%d%%, now %d%%).",
				"Your wisdom grew noticeably (+%d%%, now %d%%).",
				"This really educated you (+%d%%, now %d%%).",
				"Your mind feels more powerful (+%d%%, now %d%%).",
				"You're clearly more intelligent now (+%d%%, now %d%%).",
				"Your brain thanks you for this (+%d%%, now %d%%).",
				"You've become notably sharper (+%d%%, now %d%%).",
				"Your intellectual abilities flourished (+%d%%, now %d%%).",
			},
			big = {
				"Your intelligence jumped up (+%d%%, now %d%%).",
				"This really expanded your mind (+%d%%, now %d%%).",
				"You feel significantly smarter (+%d%%, now %d%%).",
				"A major intellectual breakthrough (+%d%%, now %d%%).",
				"Your brain is firing on all cylinders (+%d%%, now %d%%).",
				"You've gained serious knowledge (+%d%%, now %d%%).",
				"Your cognitive abilities soared (+%d%%, now %d%%).",
				"You feel like a genius (+%d%%, now %d%%).",
				"Your mind opened up dramatically (+%d%%, now %d%%).",
				"This was incredibly enlightening (+%d%%, now %d%%).",
				"Your intellect reached new heights (+%d%%, now %d%%).",
				"You're operating on a higher level (+%d%%, now %d%%).",
				"Your wisdom increased dramatically (+%d%%, now %d%%).",
				"You feel exceptionally sharp (+%d%%, now %d%%).",
				"This transformed your understanding (+%d%%, now %d%%).",
				"Your mental prowess skyrocketed (+%d%%, now %d%%).",
				"You're thinking circles around everyone (+%d%%, now %d%%).",
				"Your brain evolved significantly (+%d%%, now %d%%).",
				"Knowledge is power, and you gained lots (+%d%%, now %d%%).",
				"Your intelligence is now remarkable (+%d%%, now %d%%).",
			},
			huge = {
				"You feel downright brilliant after this (+%d%%, now %d%%).",
				"This turned you into a genius (+%d%%, now %d%%).",
				"Your intelligence reached extraordinary levels (+%d%%, now %d%%).",
				"You've unlocked your full mental potential (+%d%%, now %d%%).",
				"Your mind is operating at peak capacity (+%d%%, now %d%%).",
				"You've become incredibly wise (+%d%%, now %d%%).",
				"This was a watershed moment for your intellect (+%d%%, now %d%%).",
				"Your brain underwent a transformation (+%d%%, now %d%%).",
				"You feel like the smartest person alive (+%d%%, now %d%%).",
				"Your cognitive abilities are superhuman (+%d%%, now %d%%).",
				"Knowledge floods through every neuron (+%d%%, now %d%%).",
				"You've achieved intellectual enlightenment (+%d%%, now %d%%).",
				"Your mind has never been sharper (+%d%%, now %d%%).",
				"You see the world with new clarity (+%d%%, now %d%%).",
				"This elevated your thinking permanently (+%d%%, now %d%%).",
				"You've become a true intellectual (+%d%%, now %d%%).",
				"Your wisdom knows no bounds (+%d%%, now %d%%).",
				"You're thinking on another level entirely (+%d%%, now %d%%).",
				"Your mental evolution is complete (+%d%%, now %d%%).",
				"You've achieved genius status (+%d%%, now %d%%).",
			},
		},
		down = {
			small = {
				"You feel a bit foggy (-%d%%, now %d%%).",
				"Your focus slipped a little (-%d%%, now %d%%).",
				"A minor mental setback (-%d%%, now %d%%).",
				"Your brain feels slightly sluggish (-%d%%, now %d%%).",
				"You're thinking a tad slower (-%d%%, now %d%%).",
				"Your sharpness dimmed a bit (-%d%%, now %d%%).",
				"A small hit to your intelligence (-%d%%, now %d%%).",
				"Your mind wandered off course (-%d%%, now %d%%).",
				"You feel marginally less sharp (-%d%%, now %d%%).",
				"Your cognitive edge dulled slightly (-%d%%, now %d%%).",
				"Not your best thinking day (-%d%%, now %d%%).",
				"Your brain hiccupped a bit (-%d%%, now %d%%).",
				"You're slightly more confused (-%d%%, now %d%%).",
				"Your mental clarity dropped a touch (-%d%%, now %d%%).",
				"A minor fog settled over your mind (-%d%%, now %d%%).",
				"Your intellect took a small hit (-%d%%, now %d%%).",
				"You feel a bit scatterbrained (-%d%%, now %d%%).",
				"Your thinking isn't quite as crisp (-%d%%, now %d%%).",
				"A slight mental stumble (-%d%%, now %d%%).",
				"Your brain's running a bit slow (-%d%%, now %d%%).",
			},
			medium = {
				"You aren't thinking as clearly (-%d%%, now %d%%).",
				"This dulled your mind (-%d%%, now %d%%).",
				"Your intelligence dropped noticeably (-%d%%, now %d%%).",
				"Your focus is seriously compromised (-%d%%, now %d%%).",
				"This set back your mental growth (-%d%%, now %d%%).",
				"You feel genuinely less smart (-%d%%, now %d%%).",
				"Your brain is struggling (-%d%%, now %d%%).",
				"Your cognitive abilities suffered (-%d%%, now %d%%).",
				"You're having trouble thinking straight (-%d%%, now %d%%).",
				"Your mental sharpness declined (-%d%%, now %d%%).",
				"This clouded your judgment (-%d%%, now %d%%).",
				"You feel notably dumber (-%d%%, now %d%%).",
				"Your intellect took a real hit (-%d%%, now %d%%).",
				"Thinking is harder than before (-%d%%, now %d%%).",
				"Your mind feels heavy and slow (-%d%%, now %d%%).",
				"You're making more mistakes (-%d%%, now %d%%).",
				"Your wisdom faded noticeably (-%d%%, now %d%%).",
				"Your brain isn't cooperating (-%d%%, now %d%%).",
				"This really slowed you down mentally (-%d%%, now %d%%).",
				"Your cognitive decline is evident (-%d%%, now %d%%).",
			},
			big = {
				"Your smarts took a serious hit (-%d%%, now %d%%).",
				"You feel way less sharp than before (-%d%%, now %d%%).",
				"Your intelligence plummeted (-%d%%, now %d%%).",
				"This devastated your mental abilities (-%d%%, now %d%%).",
				"You can barely think straight (-%d%%, now %d%%).",
				"Your brain feels broken (-%d%%, now %d%%).",
				"You've forgotten more than you remember (-%d%%, now %d%%).",
				"Your cognitive functions are severely impaired (-%d%%, now %d%%).",
				"You feel genuinely stupid (-%d%%, now %d%%).",
				"This fried your brain (-%d%%, now %d%%).",
				"Your intellectual capacity collapsed (-%d%%, now %d%%).",
				"Thinking requires enormous effort (-%d%%, now %d%%).",
				"Your mind is a fog (-%d%%, now %d%%).",
				"You've lost your mental edge entirely (-%d%%, now %d%%).",
				"This was catastrophic for your intellect (-%d%%, now %d%%).",
				"Your wisdom has abandoned you (-%d%%, now %d%%).",
				"You feel mentally defeated (-%d%%, now %d%%).",
				"Your brain is barely functioning (-%d%%, now %d%%).",
				"Simple thoughts are now difficult (-%d%%, now %d%%).",
				"Your intelligence is in freefall (-%d%%, now %d%%).",
			},
			huge = {
				"This completely scrambled you (-%d%%, now %d%%).",
				"Your intelligence tanked (-%d%%, now %d%%).",
				"You feel utterly mindless (-%d%%, now %d%%).",
				"Your brain shut down completely (-%d%%, now %d%%).",
				"This destroyed your cognitive abilities (-%d%%, now %d%%).",
				"You can't form coherent thoughts (-%d%%, now %d%%).",
				"Your intellect has been obliterated (-%d%%, now %d%%).",
				"You feel brain-dead (-%d%%, now %d%%).",
				"This was a mental apocalypse (-%d%%, now %d%%).",
				"Your wisdom evaporated entirely (-%d%%, now %d%%).",
				"You've hit intellectual rock bottom (-%d%%, now %d%%).",
				"Thinking is now impossible (-%d%%, now %d%%).",
				"Your mind is a complete blank (-%d%%, now %d%%).",
				"You've lost all mental capacity (-%d%%, now %d%%).",
				"This permanently damaged your intellect (-%d%%, now %d%%).",
				"Your brain cells are on strike (-%d%%, now %d%%).",
				"You feel like you've lost decades of knowledge (-%d%%, now %d%%).",
				"Your cognitive collapse is total (-%d%%, now %d%%).",
				"You can barely remember your own name (-%d%%, now %d%%).",
				"Your intelligence has been wiped clean (-%d%%, now %d%%).",
			},
		},
	},

	Looks = {
		up = {
			small = {
				"You look a bit better in the mirror (+%d%%, now %d%%).",
				"Your appearance improved slightly (+%d%%, now %d%%).",
				"A minor glow-up occurred (+%d%%, now %d%%).",
				"You're looking marginally better (+%d%%, now %d%%).",
				"Your look got a small upgrade (+%d%%, now %d%%).",
				"People might notice you look nicer (+%d%%, now %d%%).",
				"Your attractiveness ticked up (+%d%%, now %d%%).",
				"You feel slightly more put-together (+%d%%, now %d%%).",
				"A small boost to your appearance (+%d%%, now %d%%).",
				"You're looking a tad sharper (+%d%%, now %d%%).",
				"Your style improved a bit (+%d%%, now %d%%).",
				"You caught a glimpse of a better you (+%d%%, now %d%%).",
				"Your looks got a mini upgrade (+%d%%, now %d%%).",
				"You feel marginally more attractive (+%d%%, now %d%%).",
				"A subtle improvement to your appearance (+%d%%, now %d%%).",
				"You're presenting yourself better (+%d%%, now %d%%).",
				"Your visual appeal increased slightly (+%d%%, now %d%%).",
				"You're looking fresher than before (+%d%%, now %d%%).",
				"A small win for your appearance (+%d%%, now %d%%).",
				"Your look is slightly more polished (+%d%%, now %d%%).",
			},
			medium = {
				"You had a noticeable glow-up (+%d%%, now %d%%).",
				"You're looking more put-together (+%d%%, now %d%%).",
				"Your appearance improved significantly (+%d%%, now %d%%).",
				"People are starting to notice you (+%d%%, now %d%%).",
				"You're definitely more attractive now (+%d%%, now %d%%).",
				"Your look leveled up noticeably (+%d%%, now %d%%).",
				"You feel genuinely good-looking (+%d%%, now %d%%).",
				"Your attractiveness is clearly higher (+%d%%, now %d%%).",
				"You've got a new confidence in your appearance (+%d%%, now %d%%).",
				"Your style game improved (+%d%%, now %d%%).",
				"You're turning more heads now (+%d%%, now %d%%).",
				"Your visual appeal jumped up (+%d%%, now %d%%).",
				"You look noticeably better (+%d%%, now %d%%).",
				"Your appearance is on the rise (+%d%%, now %d%%).",
				"You feel significantly more attractive (+%d%%, now %d%%).",
				"People compliment you more (+%d%%, now %d%%).",
				"Your look is working for you (+%d%%, now %d%%).",
				"You've clearly invested in yourself (+%d%%, now %d%%).",
				"Your attractiveness is undeniable now (+%d%%, now %d%%).",
				"You're becoming quite good-looking (+%d%%, now %d%%).",
			},
			big = {
				"You had a major glow-up (+%d%%, now %d%%).",
				"People are definitely noticing your looks (+%d%%, now %d%%).",
				"You're looking fantastic (+%d%%, now %d%%).",
				"Your appearance transformed dramatically (+%d%%, now %d%%).",
				"You've become genuinely attractive (+%d%%, now %d%%).",
				"Heads are turning everywhere you go (+%d%%, now %d%%).",
				"Your look is fire (+%d%%, now %d%%).",
				"You feel incredibly good-looking (+%d%%, now %d%%).",
				"Your attractiveness is through the roof (+%d%%, now %d%%).",
				"You could be a model (+%d%%, now %d%%).",
				"Your visual appeal skyrocketed (+%d%%, now %d%%).",
				"People can't stop staring (+%d%%, now %d%%).",
				"You've hit peak attractiveness (+%d%%, now %d%%).",
				"Your look is absolutely stunning (+%d%%, now %d%%).",
				"You're a certified heartthrob now (+%d%%, now %d%%).",
				"Your appearance is remarkable (+%d%%, now %d%%).",
				"You feel like a 10 out of 10 (+%d%%, now %d%%).",
				"Your glow-up is legendary (+%d%%, now %d%%).",
				"You've never looked this good (+%d%%, now %d%%).",
				"Your attractiveness is off the charts (+%d%%, now %d%%).",
			},
			huge = {
				"You're basically a model now (+%d%%, now %d%%).",
				"Your looks skyrocketed (+%d%%, now %d%%).",
				"You've achieved peak physical beauty (+%d%%, now %d%%).",
				"People are mesmerized by your appearance (+%d%%, now %d%%).",
				"Your attractiveness is legendary (+%d%%, now %d%%).",
				"You look absolutely stunning (+%d%%, now %d%%).",
				"Magazine covers would be lucky to have you (+%d%%, now %d%%).",
				"Your beauty is otherworldly (+%d%%, now %d%%).",
				"You've become drop-dead gorgeous (+%d%%, now %d%%).",
				"Your looks could launch a thousand ships (+%d%%, now %d%%).",
				"You're the most attractive person in any room (+%d%%, now %d%%).",
				"Your appearance is absolutely flawless (+%d%%, now %d%%).",
				"You've transcended normal attractiveness (+%d%%, now %d%%).",
				"Your beauty is breathtaking (+%d%%, now %d%%).",
				"You look like a Greek god/goddess (+%d%%, now %d%%).",
				"Your visual perfection is complete (+%d%%, now %d%%).",
				"You've achieved physical perfection (+%d%%, now %d%%).",
				"Your looks are unforgettable (+%d%%, now %d%%).",
				"You're walking art (+%d%%, now %d%%).",
				"Your attractiveness has reached godlike levels (+%d%%, now %d%%).",
			},
		},
		down = {
			small = {
				"You're looking a little rough (-%d%%, now %d%%).",
				"Your looks slipped slightly (-%d%%, now %d%%).",
				"A minor setback for your appearance (-%d%%, now %d%%).",
				"You feel marginally less attractive (-%d%%, now %d%%).",
				"Your look took a small hit (-%d%%, now %d%%).",
				"You're not quite as put-together (-%d%%, now %d%%).",
				"Your appearance dimmed a bit (-%d%%, now %d%%).",
				"You feel slightly less confident about your looks (-%d%%, now %d%%).",
				"A small ding to your attractiveness (-%d%%, now %d%%).",
				"You're looking a tad worn (-%d%%, now %d%%).",
				"Your visual appeal dropped slightly (-%d%%, now %d%%).",
				"Not your best look today (-%d%%, now %d%%).",
				"Your appearance suffered a bit (-%d%%, now %d%%).",
				"You feel slightly less polished (-%d%%, now %d%%).",
				"A minor blow to your looks (-%d%%, now %d%%).",
				"You're looking marginally worse (-%d%%, now %d%%).",
				"Your attractiveness took a small dip (-%d%%, now %d%%).",
				"You feel a touch less good-looking (-%d%%, now %d%%).",
				"Your style slipped a bit (-%d%%, now %d%%).",
				"A slight decline in your appearance (-%d%%, now %d%%).",
			},
			medium = {
				"This didn't do your looks any favors (-%d%%, now %d%%).",
				"You're not looking your best (-%d%%, now %d%%).",
				"Your appearance took a noticeable hit (-%d%%, now %d%%).",
				"You feel genuinely less attractive (-%d%%, now %d%%).",
				"Your looks declined significantly (-%d%%, now %d%%).",
				"People might notice you look worse (-%d%%, now %d%%).",
				"Your visual appeal dropped (-%d%%, now %d%%).",
				"You're struggling with your appearance (-%d%%, now %d%%).",
				"Your attractiveness faded noticeably (-%d%%, now %d%%).",
				"This really hurt your looks (-%d%%, now %d%%).",
				"You feel notably less good-looking (-%d%%, now %d%%).",
				"Your appearance suffered considerably (-%d%%, now %d%%).",
				"You're not turning heads anymore (-%d%%, now %d%%).",
				"Your look has seen better days (-%d%%, now %d%%).",
				"You feel less confident in your appearance (-%d%%, now %d%%).",
				"Your attractiveness is clearly lower (-%d%%, now %d%%).",
				"This wasn't kind to your looks (-%d%%, now %d%%).",
				"Your visual decline is evident (-%d%%, now %d%%).",
				"You're looking notably rougher (-%d%%, now %d%%).",
				"Your appearance took a real blow (-%d%%, now %d%%).",
			},
			big = {
				"Your looks took a major hit (-%d%%, now %d%%).",
				"You're noticeably less attractive (-%d%%, now %d%%).",
				"This devastated your appearance (-%d%%, now %d%%).",
				"You feel genuinely ugly (-%d%%, now %d%%).",
				"Your visual appeal crashed (-%d%%, now %d%%).",
				"People are avoiding eye contact (-%d%%, now %d%%).",
				"Your looks are in serious decline (-%d%%, now %d%%).",
				"This really damaged your appearance (-%d%%, now %d%%).",
				"You can't stand looking in the mirror (-%d%%, now %d%%).",
				"Your attractiveness plummeted (-%d%%, now %d%%).",
				"You feel deeply unattractive (-%d%%, now %d%%).",
				"Your appearance is struggling hard (-%d%%, now %d%%).",
				"This wrecked your looks (-%d%%, now %d%%).",
				"You're far from your best self visually (-%d%%, now %d%%).",
				"Your look is completely off (-%d%%, now %d%%).",
				"You feel like a different, worse-looking person (-%d%%, now %d%%).",
				"Your visual decline is dramatic (-%d%%, now %d%%).",
				"People are definitely noticing... negatively (-%d%%, now %d%%).",
				"Your appearance took a nosedive (-%d%%, now %d%%).",
				"You've lost a lot of your attractiveness (-%d%%, now %d%%).",
			},
			huge = {
				"This wrecked your appearance (-%d%%, now %d%%).",
				"You look completely different after this (-%d%%, now %d%%).",
				"Your looks have been destroyed (-%d%%, now %d%%).",
				"You feel utterly hideous (-%d%%, now %d%%).",
				"Your appearance collapsed completely (-%d%%, now %d%%).",
				"You can't recognize yourself anymore (-%d%%, now %d%%).",
				"Your attractiveness hit rock bottom (-%d%%, now %d%%).",
				"This permanently damaged your looks (-%d%%, now %d%%).",
				"You feel like the ugliest person alive (-%d%%, now %d%%).",
				"Your visual appeal is non-existent (-%d%%, now %d%%).",
				"People actively look away (-%d%%, now %d%%).",
				"Your appearance will never be the same (-%d%%, now %d%%).",
				"You've become unrecognizable (-%d%%, now %d%%).",
				"Your looks have been obliterated (-%d%%, now %d%%).",
				"You feel disfigured by life (-%d%%, now %d%%).",
				"Your attractiveness was annihilated (-%d%%, now %d%%).",
				"Mirrors are now your enemy (-%d%%, now %d%%).",
				"Your appearance reached its lowest point (-%d%%, now %d%%).",
				"You've never looked this bad (-%d%%, now %d%%).",
				"Your visual identity has been shattered (-%d%%, now %d%%).",
			},
		},
	},
}

----------------------------------------------------------------------
-- MONEY NARRATIVE (60+ templates)
----------------------------------------------------------------------

NarrativeContent.MoneyNarrative = {
	gain = {
		small = {
			"You picked up a bit of extra cash (%s). Your balance is now %s.",
			"You quietly added %s to your money. You now have %s.",
			"A small payday brought in %s. You're sitting at %s.",
			"You earned a modest %s. Your total is now %s.",
			"A little money came your way (%s). Balance: %s.",
			"You made %s on the side. You're at %s now.",
			"Some pocket change landed in your account (%s). Total: %s.",
			"You gained a small sum of %s. You have %s.",
			"A minor windfall of %s. Your money stands at %s.",
			"You scraped together %s. Current balance: %s.",
			"A bit of extra income (%s) found its way to you. Balance: %s.",
			"You're %s richer. Your account shows %s.",
			"A humble gain of %s. You're holding %s.",
			"You pocketed %s. Total savings: %s.",
			"Some money trickled in (%s). You're at %s.",
			"A small financial boost of %s. Balance: %s.",
			"You added %s to your wallet. Current funds: %s.",
			"A modest income of %s arrived. Your total: %s.",
			"You collected %s. Money in the bank: %s.",
			"A little extra cash (%s) came through. You have %s.",
		},
		medium = {
			"You scored a solid payout of %s. Your money climbed to %s.",
			"You made a decent chunk of money (%s). You're now at %s.",
			"That move paid off with %s. Your total is %s.",
			"A respectable sum of %s landed in your account. Balance: %s.",
			"You earned a nice %s. Your funds grew to %s.",
			"Your bank account swelled by %s. You're sitting at %s.",
			"A satisfying payday of %s. Current total: %s.",
			"You gained %s, not bad at all. You have %s.",
			"Money well earned (%s). Your balance hit %s.",
			"You're %s richer and feeling good about it. Total: %s.",
			"A meaningful income of %s. You're now worth %s.",
			"You pulled in %s. Your savings climbed to %s.",
			"Financial gains of %s. You're looking at %s.",
			"That netted you a solid %s. Balance: %s.",
			"You cashed in %s. Current holdings: %s.",
			"A profitable venture brought %s. You have %s.",
			"Your wallet got heavier by %s. Total: %s.",
			"You secured %s. Your money stands at %s.",
			"A decent haul of %s. You're at %s now.",
			"That paid out %s nicely. Balance shows %s.",
		},
		large = {
			"You hit a big financial win and gained %s. You now have %s.",
			"This was a huge payday (%s). Your balance jumped to %s.",
			"You landed a major bag of %s. You're stacked with %s.",
			"A massive windfall of %s came your way. Total: %s!",
			"You struck gold with %s. Your wealth soared to %s.",
			"Jackpot! You gained %s. You're now sitting on %s.",
			"This changed your finances (%s gained). New balance: %s!",
			"You're suddenly much richer (%s). Total wealth: %s.",
			"A life-changing sum of %s. You have %s!",
			"You made bank with %s. Your fortune is now %s.",
			"This was incredibly lucrative (%s). Balance: %s!",
			"You secured a fortune of %s. You're worth %s!",
			"Money rained down (%s). Your account shows %s!",
			"A major financial breakthrough (%s). Total: %s!",
			"You became significantly wealthier (%s). New worth: %s!",
			"That's serious money (%s). You're now at %s!",
			"Your bank account exploded with %s. Balance: %s!",
			"A huge score of %s. You're rolling in %s!",
			"Financial dreams came true (%s). Total: %s!",
			"You're %s richer! New balance: %s!",
		},
	},
	loss = {
		small = {
			"You spent a bit of cash (%s). You're left with %s.",
			"You dropped %s on this. Your balance is now %s.",
			"A small expense of %s trimmed your money to %s.",
			"You're out %s. Remaining balance: %s.",
			"A minor cost of %s. You still have %s.",
			"You paid %s for this. Current funds: %s.",
			"A little money left your pocket (%s). You have %s.",
			"You spent %s. Your savings are at %s.",
			"This cost you %s. Balance remaining: %s.",
			"A modest expense of %s. You're at %s now.",
			"You lost a small %s. Current holdings: %s.",
			"Your wallet got lighter by %s. You have %s left.",
			"A tiny dent of %s in your finances. Total: %s.",
			"You shelled out %s. Remaining: %s.",
			"A small price of %s to pay. Balance: %s.",
			"You're %s poorer now. You have %s.",
			"A minor setback of %s. Current funds: %s.",
			"You forked over %s. What's left: %s.",
			"A little spending (%s) happened. Balance: %s.",
			"This took %s from you. You still have %s.",
		},
		medium = {
			"This cost you %s. Your money fell to %s.",
			"A decent chunk of your money disappeared (%s). You're at %s.",
			"You watched %s leave your account. You're down to %s.",
			"A significant expense of %s. Your balance dropped to %s.",
			"You're out a substantial %s. Remaining: %s.",
			"This wasn't cheap (%s). You have %s left.",
			"Your finances took a hit of %s. Balance: %s.",
			"You spent a noticeable %s. Current funds: %s.",
			"Money flew out fast (%s). You're at %s now.",
			"This drained %s from you. What's left: %s.",
			"A painful expense of %s. Your total fell to %s.",
			"You felt that loss of %s. Remaining balance: %s.",
			"Your wallet is lighter by %s. You have %s.",
			"That set you back %s. Current holdings: %s.",
			"A considerable sum of %s gone. Balance: %s.",
			"You sacrificed %s for this. You're down to %s.",
			"This burned through %s. What remains: %s.",
			"Your money shrank by %s. Current total: %s.",
			"A meaningful loss of %s. You're left with %s.",
			"That hurt financially (%s). Balance: %s.",
		},
		large = {
			"You lost a massive %s. Your balance dropped to %s.",
			"This absolutely wrecked your finances (-%s). You're down to %s.",
			"Your money took a huge hit of %s, leaving you with %s.",
			"A devastating financial blow of %s. You only have %s left.",
			"You hemorrhaged %s. Your wealth crashed to %s.",
			"This was financially catastrophic (%s lost). Balance: %s.",
			"Your bank account was gutted by %s. Remaining: %s.",
			"A fortune of %s vanished. You're down to %s.",
			"You're suddenly much poorer (%s gone). What's left: %s.",
			"This wiped out %s. Your finances are at %s.",
			"A ruinous expense of %s. Current balance: %s.",
			"Your wealth evaporated by %s. You have %s.",
			"Financial disaster struck (%s lost). Remaining: %s.",
			"You watched %s disappear. You're left with just %s.",
			"This destroyed your savings (%s). Balance: %s.",
			"A massive setback of %s. Your total fell to %s.",
			"Your money was decimated by %s. What remains: %s.",
			"You're reeling from losing %s. Current funds: %s.",
			"A catastrophic loss of %s. You only have %s now.",
			"This financially ruined you (%s lost). Balance: %s.",
		},
	},
}

----------------------------------------------------------------------
-- FLAG DESCRIPTIONS (100+ life flags)
----------------------------------------------------------------------

NarrativeContent.FlagDescriptions = {
	-- POLITICAL PATH
	political_interest = "You started paying real attention to politics.",
	political_experience = "You gained your first bit of political experience.",
	political_volunteer = "You volunteered for your first political campaign.",
	campaign_donor = "You became a significant campaign donor.",
	elected_official = "You were elected to public office.",
	city_council = "You won a seat on city council.",
	mayor = "You became the mayor of your city.",
	state_representative = "You were elected to the state legislature.",
	state_senator = "You moved up to state-level politics.",
	governor = "You became the governor of your state.",
	congressman = "You became a member of Congress.",
	us_senator = "You secured a seat in the U.S. Senate.",
	vice_president = "You became the Vice President.",
	president = "You reached the highest office in the country.",
	impeached = "You were impeached from office.",
	pardoned = "You received a presidential pardon.",

	-- CRIMINAL PATH
	criminal_tendencies = "You began dipping your toes into the criminal world.",
	petty_thief = "You started stealing small things.",
	shoplifter = "You became known for shoplifting.",
	vandal = "You developed a habit of vandalism.",
	car_thief = "You picked up a reputation for stealing cars.",
	burglar = "You started breaking into homes and businesses.",
	armed_robber = "You committed armed robbery.",
	drug_dealer = "You started dealing drugs.",
	gang_prospect = "You became a prospect for a gang.",
	gang_member = "You officially joined a gang.",
	gang_captain = "You rose to captain in your gang.",
	war_veteran = "You became a hardened war veteran in gang conflicts.",
	underboss = "You rose to the rank of underboss.",
	crime_boss = "You became the boss of a criminal organization.",
	kingpin = "You became the ultimate kingpin.",
	wanted = "You're now wanted by law enforcement.",
	in_prison = "You're currently serving time in prison.",
	escaped_prison = "You escaped from prison.",
	on_parole = "You're out on parole.",
	rat = "You snitched to the authorities.",
	marked_for_death = "There's a hit out on you.",

	-- EDUCATION
	dropped_out = "You dropped out of school.",
	ged = "You got your GED.",
	high_school_diploma = "You graduated high school.",
	associate_degree = "You earned an associate's degree.",
	bachelor_degree = "You earned a bachelor's degree.",
	master_degree = "You earned a master's degree.",
	phd = "You earned a PhD.",
	medical_degree = "You became a doctor.",
	law_degree = "You became a lawyer.",
	mba = "You earned an MBA.",
	trade_certified = "You became certified in a trade.",
	honor_student = "You were recognized as an honor student.",
	valedictorian = "You became valedictorian.",
	scholarship_winner = "You won a scholarship.",
	expelled = "You were expelled from school.",

	-- CAREER
	employed = "You have a job.",
	unemployed = "You lost your job.",
	entrepreneur = "You started your own business.",
	ceo = "You became a CEO.",
	retired = "You retired from work.",
	fired = "You were fired from your job.",
	promoted = "You got promoted.",
	demoted = "You were demoted.",
	famous = "You became famous.",
	infamous = "You became infamous.",
	millionaire = "You became a millionaire.",
	billionaire = "You became a billionaire.",
	bankrupt = "You went bankrupt.",
	self_made = "You're self-made.",
	inherited_wealth = "You inherited significant wealth.",

	-- RELATIONSHIPS
	dating = "You're in a relationship.",
	engaged = "You got engaged.",
	married = "You got married.",
	divorced = "You got divorced.",
	widowed = "Your spouse passed away.",
	cheater = "You cheated on your partner.",
	cheated_on = "You were cheated on.",
	heartbroken = "You're nursing a broken heart.",
	in_love = "You're deeply in love.",
	has_kids = "You have children.",
	single_parent = "You're a single parent.",
	estranged_family = "You're estranged from your family.",
	reconciled = "You reconciled with someone important.",
	popular = "You're very popular.",
	outcast = "You're a social outcast.",
	best_friend = "You have a best friend.",
	lonely = "You're feeling lonely.",

	-- HEALTH & LIFESTYLE
	athlete = "You're an athlete.",
	obese = "You became obese.",
	fit = "You're in great physical shape.",
	addict = "You developed an addiction.",
	recovering = "You're in recovery.",
	sober = "You achieved sobriety.",
	mentally_ill = "You're struggling with mental health.",
	in_therapy = "You're in therapy.",
	survivor = "You're a survivor of something serious.",
	disabled = "You have a disability.",
	terminal_illness = "You have a terminal illness.",
	hypochondriac = "You're a hypochondriac.",
	vegetarian = "You became a vegetarian.",
	vegan = "You went vegan.",

	-- MILITARY
	enlisted = "You enlisted in the military.",
	veteran = "You're a military veteran.",
	deployed = "You were deployed overseas.",
	combat_veteran = "You saw combat.",
	honorable_discharge = "You received an honorable discharge.",
	dishonorable_discharge = "You received a dishonorable discharge.",
	war_hero = "You're a war hero.",
	ptsd = "You're dealing with PTSD.",

	-- MISC
	homeowner = "You own your home.",
	renter = "You're a renter.",
	homeless = "You became homeless.",
	car_owner = "You own a car.",
	public_transport = "You rely on public transit.",
	world_traveler = "You've traveled the world.",
	never_left_hometown = "You've never left your hometown.",
	religious = "You're religious.",
	atheist = "You're an atheist.",
	spiritualist = "You're spiritual but not religious.",
	volunteer = "You're an active volunteer.",
	activist = "You're an activist.",
	influencer = "You're a social media influencer.",
	author = "You're a published author.",
	artist = "You're a recognized artist.",
	musician = "You're a musician.",
	actor = "You're an actor.",
}

----------------------------------------------------------------------
-- YEAR RECAP TEMPLATES (BitLife-style multi-line summaries)
----------------------------------------------------------------------

NarrativeContent.YearRecapTemplates = {
	-- CHILDHOOD RECAPS
	baby = {
		"Age: %d years\nYou spent your days sleeping and crying.\nYour parents changed countless diapers.\nYou discovered your own toes.\nThe world was a blur of colors and sounds.\nEverything was new and fascinating.\nYou learned that crying gets you food.",
		"Age: %d years\nLife as a baby is simple.\nYou ate, you slept, you cried.\nYour parents looked exhausted but happy.\nYou smiled for the first time.\nSomeone always picked you up when you fussed.\nYou were blissfully unaware of everything.",
		"Age: %d years\nYou couldn't do much yet.\nBut you watched everything with wide eyes.\nYour parents made silly faces at you.\nYou tried to grab things and mostly failed.\nSleep was your best friend.\nThe world revolved around you.",
	},
	
	toddler = {
		"Age: %d years\nYou're starting to walk and talk.\nEverything in the house became climbable.\nYou said 'no' to almost everything.\nYour parents baby-proofed the entire house.\nYou discovered the joy of throwing food.\nTemper tantrums became your new skill.",
		"Age: %d years\nToddler life is full of discoveries.\nYou learned new words every day.\nYou fell down constantly but kept trying.\nYou made friends with the family pet.\nYour favorite word was 'mine.'\nNaps were your parents' favorite time.",
		"Age: %d years\nYou terrorized the household with energy.\nRunning was more fun than walking.\nYou asked 'why' approximately 500 times a day.\nYour imagination started to develop.\nEverything was a potential toy.\nYou started developing your personality.",
	},

	early_childhood = {
		"Age: %d years\nYou started making friends at preschool.\nPlaydates became a regular thing.\nYou learned your ABCs and 123s.\nYour favorite shows were on repeat.\nYou believed in Santa Claus with all your heart.\nBedtime stories were the best part of the day.",
		"Age: %d years\nKindergarten was a big adventure.\nYou made macaroni art for your parents.\nYour best friend was your entire world.\nYou skinned your knee and thought you'd die.\nSnack time was sacred.\nYou dreamed of being a superhero.",
		"Age: %d years\nChildhood was simple and sweet.\nYour biggest worry was which cartoon to watch.\nYou collected random rocks and treasures.\nHide and seek was serious business.\nYour parents were your heroes.\nLife was full of wonder and magic.",
	},

	childhood = {
		"Age: %d years\nSchool became more serious.\nYou started doing real homework.\nFriendships began to have drama.\nYou discovered your first hobby.\nParents started saying 'when I was your age...'\nYou still believed adults knew everything.",
		"Age: %d years\nElementary school life continued.\nYou learned multiplication tables.\nRecess was the best subject.\nYou had your first crush but pretended you didn't.\nBirthday parties were elaborate events.\nYou started questioning Santa Claus.",
		"Age: %d years\nYou're becoming more independent.\nYou can ride a bike without training wheels.\nYou argue with siblings constantly.\nVideo games became very important.\nYou think you know everything.\nYour room is always a mess.",
	},

	tween = {
		"Age: %d years\nMiddle school is rough.\nYou're not a kid but not a teen.\nFriendships shift constantly.\nYou're very aware of being awkward.\nSchool dances are terrifying.\nYou spend hours on the internet.",
		"Age: %d years\nYour body is changing and it's weird.\nYou care way too much what people think.\nDrama seems to follow everyone.\nYou're figuring out who you are.\nParents suddenly became embarrassing.\nMusic became very important to you.",
		"Age: %d years\nThe tween years are confusing.\nYou're caught between childhood and teen life.\nHormones are doing strange things.\nYou discovered sarcasm.\nYour room became your sanctuary.\nYou think no one understands you.",
	},

	teenage = {
		"Age: %d years\nHigh school drama is real.\nYou're figuring out your identity.\nFriendships feel more intense.\nRomantic feelings are confusing.\nYou think you're invincible.\nThe future feels both exciting and scary.",
		"Age: %d years\nTeen life is a rollercoaster.\nYou're making choices that actually matter.\nPeer pressure is constantly present.\nYou're pushing boundaries with parents.\nSocial media consumes your attention.\nYou're planning for life after high school.",
		"Age: %d years\nYou're almost an adult but not quite.\nResponsibilities are increasing.\nYou have strong opinions about everything.\nYour friend group is your chosen family.\nYou're discovering who you really are.\nThe real world is approaching fast.",
	},

	young_adult = {
		"Age: %d years\nWelcome to adulting, it's hard.\nBills are a thing now.\nYou're figuring out your career path.\nFriendships require more effort to maintain.\nYou miss how simple childhood was.\nYou realize your parents were right about some things.",
		"Age: %d years\nYoung adult life is exciting and scary.\nYou're making major life decisions.\nRelationships are getting serious.\nMoney is always on your mind.\nYou're still figuring things out.\nThe future is wide open.",
		"Age: %d years\nYou're officially an adult now.\nNo one really knows what they're doing.\nYou're building your career and life.\nSome friends are getting married.\nOthers are still figuring things out.\nYou're somewhere in between.",
	},

	adult = {
		"Age: %d years\nAdult life has settled into routine.\nWork takes up most of your time.\nYou're thinking about the future seriously.\nHealth actually matters now.\nYou value quality over quantity in friendships.\nTime seems to move faster each year.",
		"Age: %d years\nThis is what being a grown-up feels like.\nYou have responsibilities you can't escape.\nYour choices have real consequences.\nYou appreciate simple pleasures more.\nYou're becoming the person you'll always be.\nLife isn't what you expected, but it's yours.",
		"Age: %d years\nMidlife is a strange place.\nYou're not young but not old.\nYou've accumulated wisdom and regrets.\nYou think about legacy sometimes.\nOld friends are more precious.\nYou know yourself better than ever.",
	},

	senior = {
		"Age: %d years\nYou've lived a full life.\nMemories are your greatest treasure.\nHealth requires more attention.\nFamily means everything now.\nYou've seen the world change dramatically.\nYou have wisdom to share.",
		"Age: %d years\nThe golden years have arrived.\nYou've earned your rest.\nYou think about the past a lot.\nEach day is a gift.\nYou hope your legacy will last.\nLife taught you many lessons.",
		"Age: %d years\nYou've outlived many friends.\nYour body isn't what it used to be.\nBut your spirit remains strong.\nYou've made peace with your choices.\nYou treasure every moment with family.\nYou've learned what really matters.",
	},

	-- SPECIAL PATH RECAPS
	criminal_path = {
		"Age: %d years\nYou're living on the wrong side of the law.\nEvery day brings new risks.\nTrust is a luxury you can't afford.\nThe streets taught you hard lessons.\nYou look over your shoulder constantly.\nThis life isn't for everyone.",
		"Age: %d years\nThe criminal life continues.\nYou've made enemies and allies.\nMoney comes fast but danger comes faster.\nYou've done things you can't take back.\nThe law is always watching.\nYou wonder if there's another way.",
		"Age: %d years\nYou're deep in the game now.\nYour reputation precedes you.\nPower and danger are your companions.\nYou've lost people along the way.\nFreedom feels temporary.\nEvery choice led you here.",
	},

	political_path = {
		"Age: %d years\nPolitics has become your life.\nEvery handshake is calculated.\nYou're always on stage, never off.\nPower is addictive but costly.\nYou've made compromises you regret.\nThe public scrutinizes everything.",
		"Age: %d years\nClimbing the political ladder continues.\nAlliances shift like sand.\nYou're playing a long game.\nYour decisions affect thousands.\nThe pressure never truly stops.\nYou hope you're making a difference.",
		"Age: %d years\nYou've reached political heights.\nHistory will judge your choices.\nThe weight of responsibility is heavy.\nYou've sacrificed personal life for public service.\nPower came with a price.\nYou hope your legacy will be positive.",
	},

	romantic_path = {
		"Age: %d years\nLove dominates your thoughts.\nYour relationship defines much of your life.\nYou're building something with someone special.\nThe highs are incredible.\nThe challenges make you grow.\nYou can't imagine life without them.",
		"Age: %d years\nRelationship life has its ups and downs.\nYou've learned to compromise.\nYou've learned to communicate.\nLove isn't always easy.\nBut it's always worth fighting for.\nYou're grateful for your partner.",
		"Age: %d years\nYour romantic journey continues.\nYou've weathered storms together.\nThe bond has deepened over time.\nYou know each other's flaws and love anyway.\nThis is what commitment looks like.\nYou've built a life together.",
	},

	wealthy_path = {
		"Age: %d years\nMoney shapes your daily life.\nYou have options others don't.\nWealth brought comfort but not always happiness.\nYou worry about different problems than most.\nPeople treat you differently.\nYou wonder who your real friends are.",
		"Age: %d years\nThe wealthy life continues.\nLuxury becomes normalized.\nYou've learned money can't buy everything.\nYou think about legacy and impact.\nPrivilege comes with responsibility.\nYou try to use your resources wisely.",
		"Age: %d years\nYou've built significant wealth.\nFinancial worries are different now.\nYou can help others in ways most can't.\nBut you still face human problems.\nMoney didn't solve everything.\nYou've learned what truly matters.",
	},

	struggling_path = {
		"Age: %d years\nLife has been a constant struggle.\nMoney is always tight.\nYou work hard but progress is slow.\nBills pile up constantly.\nYou dream of better days.\nYou keep pushing forward.",
		"Age: %d years\nThe struggle continues but so do you.\nYou've learned to survive with less.\nResourcefulness became your strength.\nYou know the value of a dollar.\nHope keeps you going.\nYou believe things will improve.",
		"Age: %d years\nYou've faced hardship with resilience.\nNot everyone understands your journey.\nYou've learned to appreciate small victories.\nEvery step forward matters.\nYou're stronger than you know.\nThe struggle shaped who you are.",
	},
}

----------------------------------------------------------------------
-- CATEGORY FLAVOR TEXT
----------------------------------------------------------------------

NarrativeContent.CategoryFlavor = {
	school = {
		"It was another chapter in your school life.",
		"Your education journey continued.",
		"The academic world shaped you a little more.",
		"School memories were made today.",
		"Learning never stops, even when it's hard.",
	},
	family = {
		"Your family life shifted a little because of this.",
		"Family bonds were tested or strengthened.",
		"Home is where the heart is, for better or worse.",
		"Family drama is unavoidable sometimes.",
		"Your family story continues to unfold.",
	},
	work = {
		"Your career story took another step here.",
		"The professional world continues to challenge you.",
		"Work shapes more of your life than you'd like to admit.",
		"Your career path winds on.",
		"The daily grind continues.",
	},
	crime = {
		"Your criminal record quietly updated itself.",
		"The law took note of your activities.",
		"Your reputation in certain circles grew.",
		"The streets never forget.",
		"You're deeper in the game now.",
	},
	health = {
		"Your medical history just got a new entry.",
		"Your body reminded you it needs attention.",
		"Health is wealth, they say.",
		"Your wellbeing demands attention.",
		"The body keeps score.",
	},
	romance = {
		"Your heart experienced something today.",
		"Love is complicated, as always.",
		"Your romantic story continues.",
		"Matters of the heart never stay simple.",
		"Love leaves its mark, one way or another.",
	},
	social = {
		"Your social life evolved a bit.",
		"Relationships with others shifted.",
		"People in your life matter.",
		"Social connections shape who you are.",
		"Your place in the social world changed.",
	},
	money = {
		"Your financial story took a turn.",
		"Money problems (or solutions) arrived.",
		"Your wallet felt the impact.",
		"Finances are always on your mind.",
		"The economic side of life demands attention.",
	},
	random = {
		"Life threw you a curveball.",
		"The unexpected happened.",
		"You never know what's coming next.",
		"Life is full of surprises.",
		"The universe has a sense of humor.",
	},
}

----------------------------------------------------------------------
-- LIFE STAGE TRANSITIONS
----------------------------------------------------------------------

NarrativeContent.LifeStageTransitions = {
	toddler = "You're no longer a baby. The world is bigger now.",
	child = "Childhood has officially begun. Adventures await.",
	tween = "You're not a little kid anymore. Things are changing.",
	teen = "Welcome to your teenage years. Buckle up.",
	adult = "You're officially an adult now. No more excuses.",
	middle_age = "Middle age arrived. Where did the time go?",
	senior = "You've entered your senior years. Wisdom comes with age.",
	elderly = "You've lived a long life. Every day is precious.",
}

----------------------------------------------------------------------
-- RELATIONSHIP TEMPLATES
----------------------------------------------------------------------

NarrativeContent.RelationshipLines = {
	love = {
		"Your love for %s grew stronger.",
		"You and %s shared a beautiful moment.",
		"%s makes your heart skip a beat.",
		"Being with %s feels like home.",
		"Your bond with %s deepened.",
	},
	friendship = {
		"%s is always there for you.",
		"You and %s laughed until you cried.",
		"%s reminded you what true friendship means.",
		"Your friendship with %s stood the test of time.",
		"%s had your back when it mattered.",
	},
	conflict = {
		"Things with %s got complicated.",
		"You and %s had a falling out.",
		"%s isn't speaking to you right now.",
		"Trust with %s has been damaged.",
		"Your relationship with %s needs work.",
	},
	loss = {
		"You'll miss %s forever.",
		"Saying goodbye to %s was the hardest thing.",
		"%s left a hole in your life.",
		"Memories of %s will never fade.",
		"Life without %s feels empty.",
	},
}

return NarrativeContent
